name: NuGet Publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build project ContentTypeInfo
      run: dotnet build ./src/Our.Umbraco.ContentTypeInfo/Our.Umbraco.ContentTypeInfo.csproj --configuration Release
  
    - name: Pack NuGet package ContentTypeInfo
      run: dotnet pack ./src/Our.Umbraco.ContentTypeInfo/Our.Umbraco.ContentTypeInfo.csproj --configuration Release --no-build
      
    - name: Pack NuGet package ContentTypeInfo.Core
      run: dotnet pack ./src/Our.Umbraco.ContentTypeInfo.Core/Our.Umbraco.ContentTypeInfo.Core.csproj --configuration Release --no-build
      
    - name: Pack NuGet package ContentTypeInfo.Assets
      run: dotnet pack ./src/Our.Umbraco.ContentTypeInfo.Assets/Our.Umbraco.ContentTypeInfo.Assets.csproj --configuration Release --no-build

    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
