name: NuGet Publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Determine release version
      id: release
      run: |
        echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
      
    - name: Set release version
      run: echo "RELEASE_VERSION=${{ steps.release.outputs.version }}" >> $GITHUB_ENV
      
    - name: Build project ContentTypeInfo
      run: dotnet build ./src/Our.Umbraco.Community.ManagementInfo/Our.Umbraco.Community.ManagementInfo.csproj --configuration Release /p:Version=${{ steps.release.outputs.version }}
      
    - name: Build project ContentTypeInfo.Core
      run: dotnet build ./src/Our.Umbraco.Community.ManagementInfo.Core/Our.Umbraco.Community.ManagementInfo.Core.csproj --configuration Release /p:Version=${{ steps.release.outputs.version }}
      
    - name: Build project ContentTypeInfo.Assets
      run: dotnet build ./src/Our.Umbraco.Community.ManagementInfo.Assets/Our.Umbraco.Community.ManagementInfo.Assets.csproj --configuration Release /p:Version=${{ steps.release.outputs.version }}
      
    - name: Pack NuGet package ContentTypeInfo
      run: dotnet pack ./src/Our.Umbraco.Community.ManagementInfo/Our.Umbraco.Community.ManagementInfo.csproj --configuration Release --no-build /p:PackageVersion=${{ env.RELEASE_VERSION }}
      
    - name: Pack NuGet package ContentTypeInfo.Core
      run: dotnet pack ./src/Our.Umbraco.Community.ManagementInfo.Core/Our.Umbraco.Community.ManagementInfo.Core.csproj --configuration Release --no-build /p:PackageVersion=${{ env.RELEASE_VERSION }}
      
    - name: Pack NuGet package ContentTypeInfo.Assets
      run: dotnet pack ./src/Our.Umbraco.Community.ManagementInfo.Assets/Our.Umbraco.Community.ManagementInfo.Assets.csproj --configuration Release --no-build /p:PackageVersion=${{ env.RELEASE_VERSION }}

    #- name: Push NuGet package ContentTypeInfo
    #  run: dotnet nuget push ./src/Our.Umbraco.ContentTypeInfo/bin/Release/Our.Umbraco.ContentTypeInfo.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      
    #- name: Push NuGet package ContentTypeInfo.Core
    #  run: dotnet nuget push ./src/Our.Umbraco.ContentTypeInfo.Core/bin/Release/Our.Umbraco.ContentTypeInfo.Core.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      
    - name: Push NuGet package ContentTypeInfo.Assets
      run: dotnet nuget push ./src/Our.Umbraco.ContentTypeInfo.Assets/bin/Release/Our.Umbraco.ContentTypeInfo.Assets.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
